package com.example.product_api.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data; // From Lombok dependency
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * Represents a Product entity in the database.
 * Uses Lombok annotations for boilerplate code reduction (getters, setters, constructors).
 */
@Entity // Marks this class as a JPA entity, mapping it to a database table.
@Data // Lombok annotation: Generates getters, setters, toString, equals, and hashCode methods.
@NoArgsConstructor // Lombok annotation: Generates a no-argument constructor.
@AllArgsConstructor // Lombok annotation: Generates a constructor with all fields as arguments.
public class Product {

    @Id // Specifies the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the primary key to be auto-generated by the database.
    private Long id; // Unique identifier for the product.
    private String name; // Name of the product.
    private String description; // Description of the product.
    private double price; // Price of the product.
    private int quantity; // Quantity of the product in stock.
}